name: build
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8
      - run: java -version
      - run: gradle -version
      - run: gradle clean build
